### ISSUE TITLE
Error message on Topics #edit and #new

### ISSUE THREAD

**Issue by bdougie** [rapid99/Bloccit#13]
What error message are you getting. 

> _For some reason I am getting an error when going to the new and edit views for Topic. The error is stating that I am missing an 'end' but i don't have end keywords in my new and edit views for post? So I am a bit confused why I am getting this error._

**Comment by rapid99** [comment]
Syntax error in TopicsController#new and
Syntax error in TopicsController#edit

We can go over these when we meet in about an hour. 

-Matt

**Comment by rapid99** [comment]
Issue resolved
